--!strict
-- =============================================================================
-- SlimeController — STUB (scaffold session 1; implement session 3).
-- [Contract] Owns: rendering/animating ranch slimes from the WanderSim (looping
--   Tweens, never per-frame Heartbeat writes), the ProximityPrompt radial
--   (Feed/Pet/Info), and LOD swaps (DESIGN.md §5 perf budget, §7.5).
--
-- [Contract] Pattern (all client domains): a thin orchestrator (this file) +
--   focused ctx-based ModuleScripts it coordinates. Call modules through their
--   ctx.<module> handle — NEVER re-alias them as top-level locals (the
--   200-local-cap lesson, WORKFLOW.md).
-- [Contract] Never: constructs GuiObjects — ALL UI instances are authored by
--   the user in Studio; code owns logic only (WORKFLOW.md). New UI needs a
--   default-color Studio template handed off for styling.
-- =============================================================================

-- Stub: intentionally no behavior this session.
